version: '3'

services:
  blog-server:
    build: ./docker/php
    image: blog-symfony
    container_name: blog-server
    depends_on:
      - db
      - chrome
      - novnc
    volumes:
      - ./:/application:cached
      - /application/var/sessions/

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony-blog
    volumes:
      - ./tmp/db:/var/lib/mysql

  db-test:
    image: mysql:5.7
    container_name: db-test
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony-blog-test
      MYSQL_USER: gandalf
      MYSQL_PASSWORD: secret_test
    volumes:
      - ./tmp/test:/var/lib/mysql

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '8000:80'
    domainname: symfony-blog.fr
    environment:
      VIRTUAL_HOST: symfony-blog.fr
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application:cached
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - blog-server

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59-fluorine
    container_name: chrome
    volumes:
        - /dev/shm:/dev/shm
    ports:
        - "4444:4444"
        - "5901:5900"
    environment:
        VNC_NO_PASSWORD: 1

  novnc:
    image: gotget/novnc
    ports:
      - '80:6080'
    depends_on:
      - chrome
